# -*- coding: utf-8 -*-
"""Oasis_BMI_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyBWbFZR8jfbIFs6SUjAZscaXqi_QtYW
"""

#BMI CALCULATOR
# This code calculates the BMI and prints the results.

name = input("Enter your Name: ")  # Get the user's name.

weight = float(input("Enter your Weight in Kg: "))  # Get the user's weight in kilograms.

height = float(input("Enter your Height in m : "))  # Get the user's height in Metres

# Calculate the BMI.
BMI = (weight / (height ** 2))

# Print the BMI, along with a message indicating whether the user is underweight, normal weight, overweight, obese, or morbidly obese.
print('Hi ' + name + ', Your BMI is ' + str(round(BMI, 1)))

if BMI > 0:
    # Check if the BMI is in the underweight range.
    if BMI < 18.5:
        print('You are Underweight.')

    # Check if the BMI is in the normal weight range.
    elif BMI <= 24.9:
        print('You are Normal weight')

    # Check if the BMI is in the overweight range.
    elif BMI <= 29.9:
        print('You are Overweight')

    # Check if the BMI is in the obese range.
    elif BMI <= 34.9:
        print('You are Obese')

    # Check if the BMI is in the severely obese range.
    elif BMI <= 39.9:
        print('You are severely Obese')

    # Check if the BMI is in the morbidly obese range.
    elif BMI >= 40:
        print('You are Morbidly obese')

else:
    print('Invalid input. Please enter valid weight and height values.')