# -*- coding: utf-8 -*-
"""Oasis_Random_Password_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gvfg7ElKV6QNNu82Pbb1KSKp3C6sqhoP
"""

import random
import string

### function for shuffle any string value:
def random_shuffle(string_val):
    temp_string = list(string_val)

#print(temp_string)
    random.shuffle(temp_string)
    return "".join(temp_string)

def random_paasword_generator():
    uppercaseletter1 =  chr(random.randint(65,90))
    uppercaseletter2 =  chr(random.randint(65,90))

    # print('uppercaseletter2', uppercaseletter2)
    # print('uppercaseletter1', uppercaseletter1)
    lowercaseletter1 = chr(random.randint(98,120))
    lowercaseletter2 = chr(random.randint(98,120))

    # print('lowercaseletter1', lowercaseletter1)
    # print('lowercaseletter2',lowercaseletter2)
    digit1 = random.randint(20,400)
    digit2 = random.randint(20,400)

    # print('digit1', digit1)
    # print('digit2', digit2)
    punctuatuion1 = random.choice(string.punctuation)
    punctuatuion2 = random.choice(string.punctuation)

    # print('punctuatuion1', punctuatuion1)
    # print('punctuatuion2', punctuatuion2)
    password = uppercaseletter1 + uppercaseletter2 + lowercaseletter1 + lowercaseletter2 + str(digit1) + str(digit2) + punctuatuion1 + punctuatuion2
    final_password = random_shuffle(password)

    return final_password

random_paasword_generator()